version: "3.2"

services:
  app:
    build:
      context: .
    volumes:
      - log-data:/app/logs
    ports:
      - "4000:4000"

  filebeat:
    build:
      context: ./filebeat
    volumes:
      - log-data:/var/log/server
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  log-data:
